FROM postgres:9.1

#RUN rm -rf /var/lib/postgresql/data/postgresql.conf
#COPY ./postgresql.conf /var/lib/postgresql/data/

#RUN mkdir /var/lib/postgresql/data
#RUN groupadd -r postgres && useradd --no-log-init -r -g postgres postgres
#RUN chown postgres:postgres /var/lib/postgresql/data
#USER postgres

