version: '3'

services:
  app:
    build: .docker/laravel
    entrypoint: dockerize --template ./.docker/nginx.conf:./.docker/nginx/nginx.conf -wait tcp://mysql:3306 -timeout 40s ./.docker/entrypoint.sh
    environment:
      PORT: 9000
      HOST: app
    container_name: app
    volumes:
      - .:/var/www
    networks:
      - app-networks
    depends_on:
      - mysql
      - redis
  nginx:
    build: .docker/nginx
    container_name: nginx
    restart: always
    tty: true
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
    networks:
      - app-networks
    depends_on:
      - app
  redis:
    container_name: redis
    image: redis:alpine
    expose:
      - 6379
    networks:
      - app-networks
  mysql:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: mysql
    restart: always
    tty: true
    ports:
      - "33006:3306"
    volumes:
      - ./data_myql:/var/lib/mysql
    networks:
      - app-networks
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=root
networks:
  app-networks:
    driver: bridge