version: '3'

services:
  app:
    build: .
    container_name: app
    volumes:
      - .:/var/www
    depends_on:
      - nginx
      - redis
  nginx:
    build: .docker/nginx
    container_name: nginx
    restart: always
    tty: true
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
  redis:
    image: redis:alpine
    expose:
      - 6379
  db:
    image: mysql:5.6
    ports:
      - "3306:3306"
    volumes:
      - ./data_myql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=root